import { lazy } from "react";

export const HomePage = lazy(() => import("@/pages/admin/Dashboard"));
export const UsersPage = lazy(() => import("@/pages/admin/Users"));
export const AddUserPage = lazy(() => import("@/pages/admin/AddUser"));
export const VendorApprovalsPage = lazy(() => import("@/pages/admin/VendorApprovals"));
export const MessagesPage = lazy(() => import("@/pages/admin/Messages"));
export const ProfilePage = lazy(() => import("@/pages/admin/Profile"));
export const SettingsPage = lazy(() => import("@/pages/admin/Settings"));
export const RoleListPage = lazy(() => import("@/pages/admin/Roles"));
export const RoleEditPage = lazy(() => import("@/pages/admin/EditRole"));
export const AddRolePage = lazy(() => import("@/pages/admin/AddRole"));
export const ClientListPage = lazy(() => import("@/pages/admin/Clients"));
export const ClientEditPage = lazy(() => import("@/pages/admin/EditClient"));
export const PlanListPage = lazy(() => import("@/pages/admin/Plans"));
export const PlanEditPage = lazy(() => import("@/pages/admin/EditPlan"));
export const PlanCreatePage = lazy(() => import("@/pages/admin/CreatePlan"));
export const PropertyListPage = lazy(() => import("@/pages/admin/Properties"));
export const PropertyEditPage = lazy(() => import("@/pages/admin/EditProperty"));
export const AddPropertyPage = lazy(() => import("@/pages/admin/AddProperty"));
export const AddonManagementPage = lazy(() => import("@/pages/admin/AddonManagement"));
export const ReviewsPage = lazy(() => import("@/pages/admin/Reviews"));
export const Refund_policy = lazy(() => import("@/pages/admin/Refund_policy"));
