import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { Payment, Invoice, BillingStats, VendorSubscription } from '@/services/billingService';

export interface PDFGenerationOptions {
  title: string;
  subtitle?: string;
  data: any[];
  headers?: string[];
  format?: 'A4' | 'letter';
  orientation?: 'portrait' | 'landscape';
  filename?: string;
}

export class PDFGenerator {
  private doc: jsPDF;

  constructor(options: { format?: 'A4' | 'letter'; orientation?: 'portrait' | 'landscape' } = {}) {
    this.doc = new jsPDF({
      orientation: options.orientation || 'portrait',
      unit: 'mm',
      format: options.format || 'A4'
    });
  }

  private addHeader(title: string, subtitle?: string): void {
    // Add company logo/header area
    this.doc.setFillColor(59, 130, 246); // Blue color
    this.doc.rect(0, 0, this.doc.internal.pageSize.getWidth(), 40, 'F');
    
    // Title
    this.doc.setTextColor(255, 255, 255);
    this.doc.setFontSize(24);
    this.doc.setFont('helvetica', 'bold');
    this.doc.text('Squares', 20, 25);
    
    // Subtitle
    if (subtitle) {
      this.doc.setFontSize(12);
      this.doc.setFont('helvetica', 'normal');
      this.doc.text(subtitle, 20, 35);
    }
    
    // Document title
    this.doc.setTextColor(0, 0, 0);
    this.doc.setFontSize(18);
    this.doc.setFont('helvetica', 'bold');
    this.doc.text(title, 20, 60);
    
    // Date
    this.doc.setFontSize(10);
    this.doc.setFont('helvetica', 'normal');
    this.doc.text(`Generated on: ${new Date().toLocaleDateString('en-IN')}`, 20, 70);
  }

  private addFooter(pageNumber: number, totalPages: number): void {
    const pageWidth = this.doc.internal.pageSize.getWidth();
    const pageHeight = this.doc.internal.pageSize.getHeight();
    
    this.doc.setFontSize(8);
    this.doc.setTextColor(128, 128, 128);
    this.doc.text(`Page ${pageNumber} of ${totalPages}`, pageWidth / 2, pageHeight - 10, { align: 'center' });
    this.doc.text('Generated by Squares - Real Estate Management Platform', pageWidth / 2, pageHeight - 5, { align: 'center' });
  }

  generateBillingReport(
    billingStats: BillingStats,
    payments: Payment[],
    invoices: Invoice[],
    subscription: VendorSubscription | null,
    filters: { dateFrom?: string; dateTo?: string } = {}
  ): Blob {
    this.addHeader('Billing Report', 'Comprehensive financial summary');

    let yPosition = 90;

    // Stats Summary
    this.doc.setFontSize(14);
    this.doc.setFont('helvetica', 'bold');
    this.doc.text('Financial Summary', 20, yPosition);
    yPosition += 15;

    const statsData = [
      ['Total Revenue', this.formatCurrency(billingStats.totalRevenue)],
      ['Monthly Revenue', this.formatCurrency(billingStats.monthlyRevenue)],
      ['Active Subscriptions', billingStats.activeSubscriptions.toString()],
      ['Total Invoices', billingStats.totalInvoices.toString()],
      ['Paid Invoices', billingStats.paidInvoices.toString()],
      ['Overdue Invoices', billingStats.overdueInvoices.toString()],
      ['Next Billing Amount', this.formatCurrency(billingStats.nextBillingAmount)],
      ['Next Billing Date', new Date(billingStats.nextBillingDate).toLocaleDateString('en-IN')],
    ];

    autoTable(this.doc, {
      startY: yPosition,
      head: [['Metric', 'Value']],
      body: statsData,
      theme: 'striped',
      headStyles: { fillColor: [59, 130, 246] },
      styles: { fontSize: 10 },
      margin: { left: 20, right: 20 },
    });

    yPosition = (this.doc as any).lastAutoTable.finalY + 20;

    // Current Subscription
    if (subscription) {
      this.doc.setFontSize(14);
      this.doc.setFont('helvetica', 'bold');
      this.doc.text('Current Subscription', 20, yPosition);
      yPosition += 15;

      const subscriptionData = [
        ['Plan', subscription.plan?.name || 'N/A'],
        ['Status', subscription.status.charAt(0).toUpperCase() + subscription.status.slice(1)],
        ['Billing Cycle', subscription.billingCycle === 'monthly' ? 'Monthly' : 'Yearly'],
        ['Amount', this.formatCurrency(subscription.amount, subscription.currency)],
        ['Start Date', new Date(subscription.startDate).toLocaleDateString('en-IN')],
        ['End Date', new Date(subscription.endDate).toLocaleDateString('en-IN')],
        ['Auto Renewal', subscription.autoRenew ? 'Enabled' : 'Disabled'],
      ];

      autoTable(this.doc, {
        startY: yPosition,
        head: [['Detail', 'Value']],
        body: subscriptionData,
        theme: 'striped',
        headStyles: { fillColor: [16, 185, 129] },
        styles: { fontSize: 10 },
        margin: { left: 20, right: 20 },
      });

      yPosition = (this.doc as any).lastAutoTable.finalY + 20;
    }

    // Add new page for payment history if needed
    if (yPosition > 200) {
      this.doc.addPage();
      yPosition = 30;
    }

    // Payment History
    if (payments.length > 0) {
      this.doc.setFontSize(14);
      this.doc.setFont('helvetica', 'bold');
      this.doc.text('Payment History', 20, yPosition);
      yPosition += 15;

      const paymentData = payments.map(payment => [
        payment._id.slice(-8),
        payment.description,
        this.formatCurrency(payment.amount, payment.currency),
        payment.status,
        payment.paymentMethod,
        new Date(payment.createdAt).toLocaleDateString('en-IN'),
      ]);

      autoTable(this.doc, {
        startY: yPosition,
        head: [['Payment ID', 'Description', 'Amount', 'Status', 'Method', 'Date']],
        body: paymentData,
        theme: 'striped',
        headStyles: { fillColor: [245, 101, 101] },
        styles: { fontSize: 8 },
        margin: { left: 20, right: 20 },
        columnStyles: {
          0: { cellWidth: 20 },
          1: { cellWidth: 40 },
          2: { cellWidth: 25 },
          3: { cellWidth: 20 },
          4: { cellWidth: 25 },
          5: { cellWidth: 25 },
        }
      });
    }

    // Invoice History
    if (invoices.length > 0) {
      if ((this.doc as any).lastAutoTable?.finalY && (this.doc as any).lastAutoTable.finalY > 220) {
        this.doc.addPage();
        yPosition = 30;
      } else {
        yPosition = ((this.doc as any).lastAutoTable?.finalY || yPosition) + 20;
      }

      this.doc.setFontSize(14);
      this.doc.setFont('helvetica', 'bold');
      this.doc.text('Invoice History', 20, yPosition);
      yPosition += 15;

      const invoiceData = invoices.map(invoice => [
        invoice.invoiceNumber,
        this.formatCurrency(invoice.total, invoice.currency),
        invoice.status,
        new Date(invoice.issueDate).toLocaleDateString('en-IN'),
        new Date(invoice.dueDate).toLocaleDateString('en-IN'),
        invoice.paidDate ? new Date(invoice.paidDate).toLocaleDateString('en-IN') : 'Not Paid',
      ]);

      autoTable(this.doc, {
        startY: yPosition,
        head: [['Invoice #', 'Amount', 'Status', 'Issue Date', 'Due Date', 'Paid Date']],
        body: invoiceData,
        theme: 'striped',
        headStyles: { fillColor: [139, 69, 19] },
        styles: { fontSize: 8 },
        margin: { left: 20, right: 20 },
      });
    }

    // Add footer to all pages
    const totalPages = this.doc.getNumberOfPages();
    for (let i = 1; i <= totalPages; i++) {
      this.doc.setPage(i);
      this.addFooter(i, totalPages);
    }

    return new Blob([this.doc.output('blob')], { type: 'application/pdf' });
  }

  generateInvoicePDF(invoice: Invoice): Blob {
    this.addHeader(`Invoice ${invoice.invoiceNumber}`, 'Tax Invoice');

    let yPosition = 90;

    // Vendor Details
    this.doc.setFontSize(12);
    this.doc.setFont('helvetica', 'bold');
    this.doc.text('Billing To:', 20, yPosition);
    yPosition += 10;

    this.doc.setFont('helvetica', 'normal');
    this.doc.setFontSize(10);
    this.doc.text(invoice.vendorDetails.name, 20, yPosition);
    yPosition += 5;
    this.doc.text(invoice.vendorDetails.email, 20, yPosition);
    yPosition += 5;
    this.doc.text(invoice.vendorDetails.phone, 20, yPosition);
    yPosition += 5;
    this.doc.text(invoice.vendorDetails.address, 20, yPosition);
    if (invoice.vendorDetails.gst) {
      yPosition += 5;
      this.doc.text(`GST: ${invoice.vendorDetails.gst}`, 20, yPosition);
    }

    // Invoice Details
    const pageWidth = this.doc.internal.pageSize.getWidth();
    this.doc.setFont('helvetica', 'bold');
    this.doc.text('Invoice Details:', pageWidth - 80, 90);
    
    this.doc.setFont('helvetica', 'normal');
    this.doc.text(`Issue Date: ${new Date(invoice.issueDate).toLocaleDateString('en-IN')}`, pageWidth - 80, 100);
    this.doc.text(`Due Date: ${new Date(invoice.dueDate).toLocaleDateString('en-IN')}`, pageWidth - 80, 110);
    this.doc.text(`Status: ${invoice.status.toUpperCase()}`, pageWidth - 80, 120);

    yPosition += 40;

    // Invoice Items
    const itemData = invoice.items.map(item => [
      item.description,
      item.quantity.toString(),
      this.formatCurrency(item.unitPrice, invoice.currency),
      this.formatCurrency(item.total, invoice.currency),
    ]);

    autoTable(this.doc, {
      startY: yPosition,
      head: [['Description', 'Qty', 'Unit Price', 'Total']],
      body: itemData,
      theme: 'striped',
      headStyles: { fillColor: [59, 130, 246] },
      styles: { fontSize: 10 },
      margin: { left: 20, right: 20 },
    });

    // Totals
    const finalY = (this.doc as any).lastAutoTable.finalY + 10;
    const totalsData = [
      ['Subtotal', this.formatCurrency(invoice.amount, invoice.currency)],
      ['Tax', this.formatCurrency(invoice.tax, invoice.currency)],
      ['Total', this.formatCurrency(invoice.total, invoice.currency)],
    ];

    autoTable(this.doc, {
      startY: finalY,
      head: [],
      body: totalsData,
      theme: 'plain',
      styles: { fontSize: 11, fontStyle: 'bold' },
      margin: { left: pageWidth - 100, right: 20 },
      tableWidth: 80,
    });

    this.addFooter(1, 1);

    return new Blob([this.doc.output('blob')], { type: 'application/pdf' });
  }

  generatePaymentReceiptPDF(payment: Payment): Blob {
    this.addHeader('Payment Receipt', 'Transaction Confirmation');

    let yPosition = 90;

    // Payment Details
    const paymentData = [
      ['Payment ID', payment._id],
      ['Transaction ID', payment.transactionId || 'N/A'],
      ['Amount', this.formatCurrency(payment.amount, payment.currency)],
      ['Status', payment.status.charAt(0).toUpperCase() + payment.status.slice(1)],
      ['Payment Method', payment.paymentMethod.replace('_', ' ').toUpperCase()],
      ['Payment Gateway', payment.paymentGateway.toUpperCase()],
      ['Description', payment.description],
      ['Created At', new Date(payment.createdAt).toLocaleDateString('en-IN')],
    ];

    if (payment.paidAt) {
      paymentData.push(['Paid At', new Date(payment.paidAt).toLocaleDateString('en-IN')]);
    }

    autoTable(this.doc, {
      startY: yPosition,
      head: [['Detail', 'Value']],
      body: paymentData,
      theme: 'striped',
      headStyles: { fillColor: [34, 197, 94] },
      styles: { fontSize: 11 },
      margin: { left: 20, right: 20 },
    });

    // Add payment status message
    const finalY = (this.doc as any).lastAutoTable.finalY + 20;
    this.doc.setFontSize(12);
    this.doc.setFont('helvetica', 'bold');
    
    if (payment.status === 'completed') {
      this.doc.setTextColor(34, 197, 94);
      this.doc.text('✓ Payment Successful', 20, finalY);
      this.doc.setTextColor(0, 0, 0);
      this.doc.setFont('helvetica', 'normal');
      this.doc.text('Thank you for your payment. Your transaction has been processed successfully.', 20, finalY + 10);
    } else if (payment.status === 'failed') {
      this.doc.setTextColor(239, 68, 68);
      this.doc.text('✗ Payment Failed', 20, finalY);
      this.doc.setTextColor(0, 0, 0);
      this.doc.setFont('helvetica', 'normal');
      if (payment.failureReason) {
        this.doc.text(`Reason: ${payment.failureReason}`, 20, finalY + 10);
      }
    }

    this.addFooter(1, 1);

    return new Blob([this.doc.output('blob')], { type: 'application/pdf' });
  }

  private formatCurrency(amount: number, currency = 'INR'): string {
    return new Intl.NumberFormat('en-IN', {
      style: 'currency',
      currency: currency,
      minimumFractionDigits: 0,
      maximumFractionDigits: 0,
    }).format(amount);
  }
}

export const createBillingReportPDF = (
  billingStats: BillingStats,
  payments: Payment[],
  invoices: Invoice[],
  subscription: VendorSubscription | null,
  filters: { dateFrom?: string; dateTo?: string } = {}
): Blob => {
  const generator = new PDFGenerator();
  return generator.generateBillingReport(billingStats, payments, invoices, subscription, filters);
};

export const createInvoicePDF = (invoice: Invoice): Blob => {
  const generator = new PDFGenerator();
  return generator.generateInvoicePDF(invoice);
};

export const createPaymentReceiptPDF = (payment: Payment): Blob => {
  const generator = new PDFGenerator();
  return generator.generatePaymentReceiptPDF(payment);
};

export const downloadPDF = (blob: Blob, filename: string): void => {
  const url = window.URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  window.URL.revokeObjectURL(url);
};
